**Python** **Basics**

**1**. **Splitting** **the** **String** 


In [ ]:
s=" Hi there Sam!"

In [ ]:
#splits at once
s.split()

['Hi', 'there', 'Sam!']

**2.** **Use.format()** **to** **print** **the** **string**


In [ ]:
p="Earth"
diameter= 12742

In [ ]:
'The diameter of {0} is {1} kilometer'.format(p,diameter)

'The diameter of Earth is 12742 kilometer'

**3. Grab the** **word in the** **nest** **dictonary**


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


**4. Numpy**

In [ ]:
import numpy as np

**4.1 10 zero array creation**

**4.2 10 five array creation** 

In [ ]:
arr1=np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr2=np.ones(10)*5
print(arr2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**5. Create an array** **of all integers** **from 20 to 35** 

In [ ]:
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


**6. 3x3 matrix** **creation with values** **from 0 to 8**

In [ ]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**7. Concatenation** **operation**


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#concatenation
np.concatenate((A,B),axis=None)

array([1, 2, 3, 4, 5, 6])

**Pandas**

**8. Dataframe wit**h **3 rows** **and** **2 columns**

In [ ]:
import pandas as pd

In [ ]:
#numpy arrays
X = np.random.randint(10, size=(3,2))
#dataframe
df = pd.DataFrame(X,columns=['cola', 'colb'])
df

cola  colb
0     0     7
1     5     4
2     7     6

In [ ]:
#dictonary
dict_x = {
   'col_a':[1,2,3], 
   'col_b': [2,5,6], 
}
#dataframe
df = pd.DataFrame(dict_x)
df

col_a  col_b
0      1      2
1      2      5
2      3      6

In [ ]:
#list
l1 = [['Adam', 22], ['Benny', 21], ['Catherine', 26]]
#dataframe
df = pd.DataFrame(l1,columns=['Name', 'Age'])
df

Name  Age
0       Adam   22
1      Benny   21
2  Catherine   26

**9. Series** **Generation**

In [ ]:
import pandas as pd1

In [ ]:
#calling DataFrame constructor
df=pd1.DataFrame()

In [ ]:
# Create 6 dates
df['time'] = pd.date_range(start="1/1/2023",end="2/10/2023", freq ='24H')
  
# Extract features - year, month, day, hour, and minute
df['year'] = df['time'].dt.year
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day
  
# Show six rows
df.head(len(df["time"]))

time  year  month  day
0  2023-01-01  2023      1    1
1  2023-01-02  2023      1    2
2  2023-01-03  2023      1    3
3  2023-01-04  2023      1    4
4  2023-01-05  2023      1    5
5  2023-01-06  2023      1    6
6  2023-01-07  2023      1    7
7  2023-01-08  2023      1    8
8  2023-01-09  2023      1    9
9  2023-01-10  2023      1   10
10 2023-01-11  2023      1   11
11 2023-01-12  2023      1   12
12 2023-01-13  2023      1   13
13 2023-01-14  2023      1   14
14 2023-01-15  2023      1   15
15 2023-01-16  2023      1   16
16 2023-01-17  2023      1   17
17 2023-01-18  2023      1   18
18 2023-01-19  2023      1   19
19 2023-01-20  2023      1   20
20 2023-01-21  2023      1   21
21 2023-01-22  2023      1   22
22 2023-01-23  2023      1   23
23 2023-01-24  2023      1   24
24 2023-01-25  2023      1   25
25 2023-01-26  2023      1   26
26 2023-01-27  2023      1   27
27 2023-01-28  2023      1   28
28 2023-01-29  2023      1   29
29 2023-01-30  2023      1   30
30 2023-01-31  2023      1   31
31 2023-02-01  2023      2    1
32 2023-02-02  2023      2    2
33 2023-02-03  2023      2    3
34 2023-02-04  2023      2    4
35 2023-02-05  2023      2    5
36 2023-02-06  2023      2    6
37 2023-02-07  2023      2    7
38 2023-02-08  2023      2    8
39 2023-02-09  2023      2    9
40 2023-02-10  2023      2   10

**10.** **2D List to** **Dataframe**

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df=pd1.DataFrame(lists,columns=['column1','column2','column3'])
df


column1 column2  column3
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24